import './globals.css';
import type { Metadata } from 'next';
import { Toaster } from '@/components/ui/sonner';
import { AuthProviders } from '@/components/auth/AuthProviders';
import { TRPCProvider } from '@/trpc/client/Provider';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <AuthProviders>
                    <TRPCProvider>
                        {children}
                        <Toaster />
                    </TRPCProvider>
                </AuthProviders>
            </body>
        </html>
    );
}
